@startuml Architecture

!include <C4/C4_Container>
skinparam Linetype polyline
skinparam wrapWidth 900

Person(client, "Заявитель")
Person(user, "Пользователь")

System_Boundary(serviceKCR, "Барс-имущество 3.0"){
    ContainerQueue(api, "API Gateway", "Nginx", "Взаимодействие с внешними сервисами, аутентификация клиентов и пользователей")
    ContainerQueue(kafka, "Kafka Broker", "Kafka", "Брокер сообщений для обмена данными между сервисами")
    Container(barsDesktop, "Desktop App", "Java", "Десктоп приложение для доступа к функциям системы")
    
    Boundary(msService, "Сервис услуг"){
        Container(serviceKcr, "Provision service", "Java", "Сервис для оказания услуг заявителей")
        ContainerDb(dbServiceKcr, "Provision service database", "PostgreSQL", "Хранение информации об услугах (ЦАР)")
    }
    Boundary(monolit, "Монолит"){
        Container(serviceMonolit, "Monolit", "Java", "Монолит, основная БЛ")
        ContainerDb(dbMonolit, "Monolit database", "PostgreSQL", "Хранение данных")
    }
    Boundary(msMicrosmev, "Микросмэв"){
        Container(microsmev, "Microsmev service", "Java", "Сервис взаимодействия с внешними системами через СМЭВ")
        ContainerDb(dbMicrosmev, "Microsmev database", "PostgreSQL", "Хранение данных межвед. запросов")
    }   
}

System_Ext(epgu, "ЕПГУ", "Портал госуслуг")
System_Ext(mfc, "МФЦ", "Многофункциональный центр")

Rel_D(user, barsDesktop, " ")

Rel_D(client, epgu, "Подать заявление")
Rel_D(client, mfc, "Подать заявление")
Rel_D(client, user, "Подать заявление (лично)")

BiRel_D(serviceKcr, dbServiceKcr, "Чтение и запись в БД", "ODBC")
BiRel_D(serviceMonolit, dbMonolit, "Чтение и запись в БД", "ODBC")
BiRel_D(microsmev, dbMicrosmev, "Чтение и запись в БД", "ODBC")

BiRel_D(serviceMonolit, kafka, "Отправка/получение сообщений", "Kafka")
BiRel_D(microsmev, kafka, "Отправка/получение сообщений", "Kafka")
BiRel_D(serviceKcr, kafka, "Отправка/получение сообщений", "Kafka")

Rel_D(barsDesktop, serviceMonolit, "Аутентификация/авторизация", "HTTPS")

BiRel_D(mfc, microsmev, "Получение/отправка информации", "SOAP")
BiRel_D(epgu, microsmev, "Получение/отправка информации", "SOAP")

Rel_D(api, serviceKcr, "Работа с услугами (ЦАР)", "REST/HTTP")
Rel_D(api, serviceMonolit, "Доступ к основному функционалу", "REST/HTTP")
Rel_D(api, microsmev, "Отправка запросов в межвед.органы через СМЭВ", "REST/HTTP")

@enduml