@startuml

skinparam linetype ortho

Entity Пользователь {
  *Имя
  *АДБ
}

Enum Тип_пользователя{
  *Администратор
  *Пользователь
}

Entity Заявитель {
  *Имя
  *ИНН
  *КПП
  *ОГРН
  *Юридический адрес
}

Enum Тип_заявителя{
  *ФЛ
  *ЮЛ
  *Представитель заявителя
}

Entity Заявление {
  *Дата_подачи
  *Номер регистрации
  *Дата результата
  *Срок предоставления
}

Enum Способ_подачи{
  *ЕПГУ
  *Лично
  *МФЦ
}

Enum Статус_заявления_ЕПГУ {
  *Заявление отправлено в ведомство
  *Заявление получено ведомством
  *Заявление требует исправления
  *Отказ в приеме
  *Заявление зарегистрировано
  *Отказано в предоставлении услуги
  *Принято решение о предоставлении услуги
  *Результат выдан заявителю в ведомстве
  *Результат получен в МФЦ. Ожидание выдачи заявителю
  *Результат выдан заявителю в МФЦ
}

Entity ЦАР {
  *Номер
  *Назначение
  *Версия
}




Заявитель "*" --> "1" Тип_заявителя
Заявитель "1" --> "*" Заявление
Заявление "*" --> "1" Статус_заявления_ЕПГУ
ЦАР "1" --> "*" Заявление 
Заявление "*" --> "1" Способ_подачи
Пользователь "*" --> "1" Тип_пользователя




@enduml