@startuml

'hide footbox
skinparam {
    MaxMessageSize 200
}
skinparam sequence{
    ParticipantPadding 30
    MessageAlign center
}
autonumber "<b>[0]"

actor Пользователь
participant Фронт_монолит
participant Бэк_монолит
participant Сервис_услуг
participant БД_сервис_услуг
participant Микросмэв


Пользователь++
Пользователь -> Фронт_монолит++: Загрузить ЦАР через СМЭВ
Фронт_монолит -> Бэк_монолит++: Получить форму для запроса ЦАР
Бэк_монолит -> Фронт_монолит--:  Отправка формы
Фронт_монолит -> Пользователь--: Отрисовка формы
Пользователь -> Пользователь: Ввод номер ЦАР в форму
Пользователь -> Фронт_монолит++: Отправить запрос
Фронт_монолит -> Бэк_монолит++: Отправить запрос
Бэк_монолит -> Микросмэв++: Отправить запрос
Микросмэв -> Бэк_монолит--: Запрос поставлен в очередь на обработку
Бэк_монолит -> Фронт_монолит--: Выведи запрос поставлен в очередь на обработку
Фронт_монолит -> Пользователь--: Запрос поставлен в очередь на обработку
Пользователь--
par async
 Микросмэв -> Микросмэв++: Обработка
 Микросмэв -> Сервис_услуг++: Вебхук ЦАР
 Микросмэв--
 Сервис_услуг -> Сервис_услуг: Обработка
 Сервис_услуг -> БД_сервис_услуг--: Запись
end par
@enduml