@startuml

actor Пользователь
participant Фронт_монолит
participant Бэк_монолит
participant Сервис_услуг
participant БД_сервис_услуг

Пользователь -> Фронт_монолит: Загрузить ЦАР в формате XML
Фронт_монолит -> Пользователь: Открывается проводник ОС
Пользователь -> Пользователь: Выбрать XML
Пользователь -> Фронт_монолит: Подтвердить выбранный XML
Фронт_монолит -> Бэк_монолит: Отправить выбранный XML
Бэк_монолит -> Сервис_услуг: Отправить выбранный XML
Сервис_услуг -> Сервис_услуг: Обработка XML

alt Успешная загрузка
    Сервис_услуг -> БД_сервис_услуг: Загрузка ЦАР в БД
    Сервис_услуг -> Бэк_монолит: Загрузка ЦАР 200 OK
    Бэк_монолит -> Фронт_монолит: Вывести успешная загрузка ЦАР
    Фронт_монолит -> Пользователь: Вывод информации об успешной загрузка ЦАР
else Некорректный файл
    Сервис_услуг -> Бэк_монолит: Некорректный формат или файл поврежден
    Бэк_монолит -> Фронт_монолит: Вывести информацию об ошибке при загрузка ЦАР
    Фронт_монолит -> Пользователь: Вывод информации об ошибке при загрузка ЦАР
end
@enduml
