openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SONORAME2_1/Provision_service/1.0.0
info:
  version: "1.0.0"
  title: Provision service API
  description: API спецификация для сервиса услуг
paths:
  /services:
    get:
      tags:
      - Сервис услуг
      summary: Получить список услуг и подуслуг
      security: []
      description: Получение списка услуг и подуслуг
      operationId: get_services
      parameters:
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id_response:
                    type: integer
                  sys_component:
                    type: string
                  service_list:
                    type: array
                    items:
                      type: object
                      properties:
                        service_info:
                          type: object
                          properties:
                            service_name:
                              type: string
                            service_id:
                              type: string
                            service_descr:
                              type: string
                            service_level:
                              type: string
                            # и т.д. для других свойств
                        subservice_list:
                          type: array
                          items:
                            type: object
                            properties:
                              subservice_name:
                                type: string
                              max_period:
                                type: integer
                              max_period_units:
                                type: string
                              # и т.д. для других свойств
        '404':
          $ref: '#/components/responses/404'
  /services/stages:
    post:
      tags:
        - Сервис услуг
      summary: Создать информацию об этапе целевой услуги
      description: Создать информацию о целевом этапе целевой подуслуги
      operationId: create_stage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message_id_request:
                  type: integer
                  description: Идентификатор сообщения запроса
                sys_component:
                  type: string
                  description: Системный компонент
                service_id:
                  type: string
                  description: Идентификатор услуги (регламента)
                sub_service_id:
                  type: string
                  description: Идентификатор подуслуги
                service_stage_id:
                  type: integer
                  description: Идентификатор текущего этапа обращения
      responses:
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '401':
          $ref: '#/components/responses/401'
        '200':
          $ref: '#/components/responses/200'
  /services/events:
    post:
      tags:
        - Сервис услуг
      summary: Создать описание события с учетом результата текущего этапа
      description: Создать описание необходимого события с учетом результата текущего этапа.
      operationId: create_events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message_id_request:
                  type: integer
                sys_component:
                  type: string
                service_id:
                  type: string
                sub_service_id:
                  type: string
                service_stage_id:
                  type: integer
                service_result:
                  type: object
                  properties:
                    result_name:
                      type: string
                    result_id:
                      type: string
      responses:
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
        '401':
          $ref: '#/components/responses/401'
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id_response:
                    type: integer
                  sys_component:
                    type: string
                  operations:
                    type: array
                    items:
                      type: object
                      properties:
                        operation_name:
                          type: string
                        operation_id:
                          type: string
                        operation_type:
                          type: string
                        operation_info:
                          type: object
                          properties:
                            stage_name:
                              type: string
                            stage_id:
                              type: string
                            status_name:
                              type: string
                            smev_message_namespace:
                              type: string
                            user_list:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  name:
                                    type: string
                            push_message:
                              type: string
  /services/{serviceId}:
    get:
      tags:
        - Сервис услуг
      summary: Получить информацию об определенной услуге
      description: Получить информацию о конкретной услуге по её уникальному идентификатору
      operationId: get_service_by_id
      parameters:
      - $ref: '#/components/parameters/serviceId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id_response:
                    type: integer
                  sys_component:
                    type: string
                  service_list:
                    type: array
                    items:
                      type: object
                      properties:
                        service_info:
                          type: object
                          properties:
                            service_name:
                              type: string
                            service_id:
                              type: string
                            service_descr:
                              type: string
                            service_level:
                              type: string
                            # и т.д. для других свойств
                        subservice_list:
                          type: array
                          items:
                            type: object
                            properties:
                              subservice_name:
                                type: string
                              max_period:
                                type: integer
                              max_period_units:
                                type: string
                              # и т.д. для других свойств
        404:
          $ref: '#/components/responses/404'
          
components:
  responses:
    '404':
      description: Что-то пошло не так...
      content:
        application/json:
          schema:
            required:
            - code
            - errorId
            - messageEn
            - messageRu
            type: object
            properties:
              errorId:
                type: integer
              code:
                maximum: 599
                minimum: 400
                type: integer
              messageRu:
                maxLength: 500
                minLength: 1
                pattern: "([А-Яа-я0-9-]+)"
                type: string
                nullable: false
              messageEn:
                maxLength: 500
                minLength: 1
                pattern: "([A-Za-z0-9-]+)"
                type: string
                nullable: false
            description: Текст сообщения об ошибке
    '422':
      description: Ошибка бизнес-логики
      content:
        application/json:
          schema:
            required:
            - code
            - message
            type: object
            properties:
              code:
                type: integer
                description: Код ошибки
              message:
                type: string
                description: Подробности ошибки
                example: Невозможно получить статусы.
    '401':
      description: Недостаточно прав
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              message_id_response:
                type: integer
              sys_component:
                type: string
              table_settings:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        can_update:
                          type: boolean
              table_data:
                type: array
                items:
                  type: object
                  properties:
                    value:
                      type: string
                    mask:
                      type: string
                    type:
                      type: string
                    on_click_operation:
                      type: object
  parameters:
    serviceId:
      name: serviceId
      in: path
      description: Уникальный ID регламента
      required: true
      style: simple
      explode: false
      schema:
        type: string
    offsetParam:
      name: offset
      in: query
      description: Номер первого элемента на странице
      required: false
      style: form
      explode: true
      schema:
        minimum: 1
        type: integer
        default: 1
    limitParam:
      name: limit
      in: query
      description: Количество элементов на странице
      required: false
      style: form
      explode: true
      schema:
        maximum: 100
        minimum: 5
        type: integer
        default: 20
  securitySchemes:
    apiKey:
      type: apiKey
      name: apiKey
      in: query
      
security:
  - apiKey: []
externalDocs:
  url: https://sonorame.github.io/docs_kcr
