@startuml

'hide footbox
skinparam {
    MaxMessageSize 200
}
skinparam sequence{
    ParticipantPadding 30
    MessageAlign center
}
autonumber "<b>[0]"

actor Пользователь
participant Фронт_монолит
participant Бэк_монолит
participant БД_монолита
participant Кафка
participant Микросмэв

Пользователь -> Фронт_монолит: Зарегистрировать обращение
Фронт_монолит -> Бэк_монолит: Запрос на регистрацию обращения
Бэк_монолит -> БД_монолита: Обновить статус обращения
Бэк_монолит -> Фронт_монолит: Обращение зарегистрировано, обновить вкладку
alt Запросы направлены автоматически
    Бэк_монолит -> Кафка: Очередь отправить межведомственные запросы
end
Фронт_монолит -> Пользователь: Сообщение зарегистрированно + вкладка "Межведомственное взаимодействие"
Пользователь -> Пользователь: Перейти на вкладку "Межведомственное взаимодействие"
Пользователь -> Фронт_монолит: Отправить запросы
Фронт_монолит -> Бэк_монолит: Отправить межведомственные запросы
Бэк_монолит -> Кафка: Очередь отправить межведомственные запросы
Микросмэв ->> Кафка: async Обработка запросов
Бэк_монолит -> БД_монолита: Обновить статус заявления
Бэк_монолит -> Фронт_монолит: Запросы направлены
Фронт_монолит -> Пользователь: Запросы направлены


@enduml